#!/usr/bin/env python3
"""
Regenerate INDEX.md from whatever is on disk under research/.

The index is the entry point to the archive: one row per research day, showing
how far that day's pipeline got and what the headline call was. It is derived
state — safe to delete and rebuild at any time.

    python3 scripts/update_index.py
"""

import glob
import json
import os
import re
from datetime import datetime, timezone

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESEARCH = os.path.join(REPO_ROOT, "research")
MAX_ROWS = 180  # roughly nine months of trading days


def _read_json(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return None


def _headline(advice):
    """Best single line describing the day's top call."""
    if not advice:
        return ""
    picks = advice.get("ranked_names") or advice.get("panel_results") or []
    if not picks:
        return ""
    top = picks[0]
    ticker = top.get("ticker", "?")
    call = top.get("call", "?")
    move = top.get("signed_estimated_move")
    move_s = f" {move:+.1f}%" if isinstance(move, (int, float)) else ""
    certainty = top.get("certainty_tier", "")
    return f"`{ticker}` {call}{move_s}" + (f" ({certainty})" if certainty else "")


def collect():
    rows = []
    for run_dir in sorted(glob.glob(os.path.join(RESEARCH, "*", "*", "*")), reverse=True):
        day = os.path.basename(run_dir)
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", day):
            continue

        universe = _read_json(os.path.join(run_dir, "00-universe.json"))
        shortlist = _read_json(os.path.join(run_dir, "01-shortlist.json"))
        advice = _read_json(os.path.join(run_dir, "04-advice.json"))

        n_universe = (universe or {}).get("counts", {}).get("total", "")
        n_short = len((shortlist or {}).get("shortlist", []) or []) or ""
        n_dossiers = len(glob.glob(os.path.join(run_dir, "02-dossiers", "*.md")))
        n_panels = len(glob.glob(os.path.join(run_dir, "03-panel", "*.json")))
        has_advice = os.path.exists(os.path.join(run_dir, "04-advice.md"))
        has_outcome = os.path.exists(os.path.join(run_dir, "05-outcome.md"))

        stages = "".join([
            "U" if universe else "·",
            "T" if shortlist else "·",
            "D" if n_dossiers else "·",
            "P" if n_panels else "·",
            "A" if has_advice else "·",
            "O" if has_outcome else "·",
        ])

        rel = os.path.relpath(run_dir, REPO_ROOT)
        rows.append({
            "day": day,
            "rel": rel,
            "stages": stages,
            "n_universe": n_universe,
            "n_short": n_short,
            "n_dossiers": n_dossiers or "",
            "n_panels": n_panels or "",
            "headline": _headline(advice),
        })
    return rows


def render(rows):
    out = [
        "# Earnings research archive",
        "",
        "One row per research day, newest first. Regenerated by "
        "`scripts/update_index.py` — do not hand-edit.",
        "",
        f"_Last updated: {datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC · "
        f"{len(rows)} run(s) on record._",
        "",
        "Stage column reads `UTDPAO`: **U**niverse, **T**riage, **D**ossiers, "
        "**P**anel, **A**dvice, **O**utcome. A `·` means that stage did not produce output.",
        "",
        "| Date | Stages | Universe | Shortlist | Dossiers | Panels | Top call |",
        "| --- | :---: | ---: | ---: | ---: | ---: | --- |",
    ]
    for r in rows[:MAX_ROWS]:
        out.append(
            f"| [{r['day']}]({r['rel']}/) | `{r['stages']}` | {r['n_universe']} | "
            f"{r['n_short']} | {r['n_dossiers']} | {r['n_panels']} | {r['headline']} |"
        )
    if len(rows) > MAX_ROWS:
        out += ["", f"_{len(rows) - MAX_ROWS} older run(s) not shown; browse `research/`._"]
    out += [
        "",
        "---",
        "",
        "This archive is research output, not financial advice.",
        "",
    ]
    return "\n".join(out)


def main():
    rows = collect()
    with open(os.path.join(REPO_ROOT, "INDEX.md"), "w", encoding="utf-8") as fh:
        fh.write(render(rows))
    print(f"INDEX.md rebuilt with {len(rows)} run(s)")


if __name__ == "__main__":
    main()
